//buildspec.yml
version: 0.2
phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm test
artifacts:
  files:
    - '**/*'
    $response = $this->s3->putObject(
[
'Bucket' => $mytestingproject,
'Key' => $mytestingproject,
'SourceFile' => $tempFilePath,
'ContentType' => 'image/png',
'ACL' => 'public-read',
'StorageClass' => 'REDUCED_REDUNDANCY'
]
);

'ACL' => 'public-read',
{
  "Version": "2012-10-17",
  "Id": "...",
  "Statement": [
    ### BEGIN ADDING STATEMENT HERE ###
    {
      "Effect": "Allow",
      "Action": [
        "s3:DeleteBucket",
        "s3:DeleteObject"
      ],
      "Resource": "*"
    }
    ### END ADDING STATEMENT HERE ###
  ]
}
