//buildspec.yml
version: 0.2
phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm test
artifacts:
  files:
    - '**/*'
    $response = $this->s3->putObject(
[
'Bucket' => $mytestingproject,
'Key' => $mytestingproject,
'SourceFile' => $tempFilePath,
'ContentType' => 'image/png',
'ACL' => 'public-read',
'StorageClass' => 'REDUCED_REDUNDANCY'
]
);

'ACL' => 'public-read',
